### ISSUE TITLE
Set up script fails if you do not have a Scripts folder

### ISSUE THREAD

**Issue by joeytepp** [chrismaltais/vsc-ssps#1]
## Description
While installing this sweet script I noticed that it failed since I didn't have a Scripts folder yet.

## Steps to reproduce
1. Remove the `~/Library/Scripts` folder (or move it somewhere else temporarily)
2. Run the `setup.sh` script
3. Notice that there is a failure due to `No such file or directory`

**Comment by chrismaltais** [comment]
Added a line to create the directory if it's not present (using `mkdir -p`)
Should work now! :)
